### ISSUE TITLE
Using a GitHub Action instead of the Azure Function

### ISSUE THREAD

**Issue by softworkz** [gitgitgadget/gitgitgadget#809]
I was looking for a way to avoid setting up the Azure Function in addition to all the other components that are already part of this setup, so I was hoping to find a way that is using some of the existing components.

The solution that I'm showing is a small GitHub Action workflow and the obvious drawback is that it needs to be included in the repository files, that's unavoidable and the GitHub roadmap indicates that this won't change shortly.

Here's the workflow file (main.yml)

```yml
# This workflow invokes an Azure Pipeline for certain issue_comment events

name: gitgitgadget

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issue_comment:
    types: [created, edited]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ github.event.comment.user.type != 'Bot' }} && ${{ github.event.issue.pull_request }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: GitHub Script
        uses: actions/github-script@v5.0.0
        id: stringify
        with:
          script: |
            console.log(context.payload)
            return Buffer.from(JSON.stringify(context.payload)).toString('base64')
          result-encoding: string
      - name: Trigger Azure Release Pipeline
        uses: alexrster/pipelines@v2
        with:
          # Fullyqualified URL to the Azure DevOps organization along with project name
          # The secret needs to be the 'organization/project' part on DevOps
          azure-devops-project-url: https://dev.azure.com/${{ secrets.azure_devops_org_project }}

          # Name of the Azure Pipline to be triggered
          azure-pipeline-name: ${{ secrets.azure_devops_pipeline }}

          # Set/Overwrite pipeline variables
          azure-pipeline-variables: '{ "pr.comment.id": "${{ github.event.comment.id }}", "sourceBranch": "refs/pull/${{ github.event.issue.number }}/head", "payload": "${{ steps.stringify.outputs.result }}" }'

          # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
          azure-devops-token: ${{ secrets.azure_devops_token }}
```
